services:
  # Backend (Servidor de Node.js)
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false

  # Frontend (Sitio Estático de React)
  - type: static_site
    name: frontend
    env: node
    plan: free
    buildCommand: "npm run build"
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_WEBSOCKET_URL
        fromService:
          type: web
          name: backend
          property: url
